// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		double result;
		int big=0;
		int smallOrEqual=0;
		while (N>0) {
			result = Math.random();
			if (result>0.5)
			big= big+1;
			else
			smallOrEqual= smallOrEqual+1;
			N=N-1;
		}
			System.out.println ("> 0.5: "+ big);
			System.out.println ("<= 0.5: "+ smallOrEqual);
		if  (big!=0 && smallOrEqual!=0)  
		{
			double ratio;
			if (big<smallOrEqual)
			ratio = (double) big/smallOrEqual;
			else
				ratio = (double) smallOrEqual/big;
			System.out.println("Ratio: " + ratio);
		}


	}
}
